spring:
  application:
    name: contact-service
  jpa:
    hibernate:
      ddl-auto: ${DDL_STRATEGY:create-drop}
    properties:
      hibernate:
        dialect: ${JPA_DIALECT:org.hibernate.dialect.MySQL57Dialect}
        show_sql: ${HIBERNATE_SHOW_SQL:true}
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  datasource:
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:pass}
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/local?allowPublicKeyRetrieval=true&useSSL=false}
  h2:
    console.enabled: true
    console.path: /h2-console
  output:
   ansi:
    enabled: ALWAYS
#Logging properties
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
  file:
    max-size: 2MB
    name: ${LOG_FILE_NAME:logs/contacts.log}

# You can override the values with environment variables
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/contact-service}